### ISSUE TITLE
Random number generator is not generating random numbers.

### ISSUE THREAD

**Issue by mytechnotalent** [microbit-foundation/micropython-microbit-v2#53] opened 2020-12-26 14:48 UTC
```
import random

random_number = random.randint(1, 20)
print(random_number)
```

It is printing the same one random number.  In this case it is 7 @microbit-carlos as we discussed.

**Comment by carlosperate** [comment] 2020-12-26 15:07
uBit.init should be seeding the random number generator:
https://github.com/microbit-foundation/micropython-microbit-v2/blob/0c4287ca33702f85917bd706067a6ca41a21510f/src/codal_app/main.cpp#L52-L53
https://github.com/lancaster-university/codal-microbit-v2/blob/d49c441bb712bc02bf2c7e4d95b757721eb54e4a/model/MicroBit.cpp#L169

**Comment by dpgeorge** [comment] 2021-01-05 21:07
> It is printing the same one random number.

Do you mean it prints the same number each time it starts up?  Calling `randint()` again and again should return different values.

Note that the `random` module uses its own pseudo-RNG, not anything from CODAL.

**Comment by mytechnotalent** [comment] 2021-01-05 21:18
@dpgeorge when I literally reboot the micro:bit it picks the same number every time.  Yes when it starts up.  I was hoping we can avoid having to call `randint()` twice if possible.

**Comment by dpgeorge** [comment] 2021-01-05 22:25
Ok.  I think the issue is that the `random` module uses the same PRNG sequence each time it starts up.  This needs to be fixed so that it seeds itself from a true random source.

**Comment by mytechnotalent** [comment] 2021-01-17 01:35
Any progress on this?  I am working on many micro:python tutorials but the random number generator is failing as stated?

**Comment by dpgeorge** [comment] 2021-01-17 05:38
This should be fixed by b621de7b349d248bdaea4a551fd75d956a1bbe27 (I was not able to test it).

**Comment by jaustin** [comment] 2021-01-20 18:02
@mytechnotalent Does the 'thumbs up' mean it works for you? Just want to be explicit before I close the issue, or go to test it myself :)

**Comment by mytechnotalent** [comment] 2021-01-20 18:12
@jaustin my apologies!  I did `git checkout b621de7` and compile and test...
```
>>> randint(1, 5)
1
>>> randint(1, 5)
4
>>> randint(1, 5)
5
>>> randint(1, 5)
2
>>> 
```

@dpgeorge change did in fact fix.  This is tested and good to merge to main.

**Closed** 2021-01-20 18:18 UTC
